---
- hosts: localhost
  become: true
  tasks:
  - name: Install python3-venv
    package:
      name: python3-venv
      state: present
  - name: Install Bloodhound
    package:
      name: bloodhound
      state: present
  - name: Install FileZilla
    package:
      name: filezilla
      state: present
  - name: Install Remmina
    package:
      name: remmina
      state: present
  - name: Install Docker
    package:
      name: docker.io
      state: present
  - name: Install Gobuster
    package: 
      name: gobuster
      state: present
  - name: Install Seclists
    package:
      name: seclists
      state: present
  - name: Install Feroxbuster
    package:
      name: feroxbuster
      state: present
  - name: Install oscanner
    package:
      name: oscanner
      state: present
  - name: Install Redis Tools
    package:
      name: redis-tools
      state: present
  - name: Install sipvicious
    package:
      name: sipvicious 
      state: present
  - name: Install tnscmd10g
    package:
      name: tnscmd10g 
      state: present  
  - name: Install wkhtmltopdf
    package:
      name: wkhtmltopdf 
      state: present
  - name: Install xclip
    package:
      name: xclip 
      state: present
  - name: Install chisel
    package:
      name: chisel 
      state: present
  - name: Install mingw-w64
    package:
      name: mingw-w64 
      state: present
  - name: Install guake
    package:
      name: guake
      state: present
  - name: Install dconf-cli
    package:
      name: dconf-cli
      state: present
  - name: Install gnome-font-viewer
    package:
      name: gnome-font-viewer
      state: present
  - name: Install Visual Studio
    apt:
      deb: https://az764295.vo.msecnd.net/stable/30d9c6cd9483b2cc586687151bcbcd635f373630/code_1.68.1-1655263094_amd64.deb
  - name: Copy a ZSH profile
    ansible.builtin.copy:
      src: /home/kali/Kali_Build/.zshrc
      dest: /home/kali/.zshrc
      owner: kali
      group: kali
      mode: '0644'
  - name: Copy a Tmux profile
    ansible.builtin.copy:
      src: /home/kali/Kali_Build/.tmux.conf
      dest: /home/kali/.tmux.conf
      owner: kali
      group: kali
      mode: '0644'
  - name: Clone SQLMap github repository
    git:
      repo: https://github.com/sqlmapproject/sqlmap.git
      dest: /home/ubuntu/sqlmap/
      clone: yes
      update: yes
  - name: Clone tmux-plugin tpm github repository
    git:
      repo: https://github.com/tmux-plugins/tpm
      dest: ~/.tmux/plugins/tpm
      clone: yes
      update: yes
  - name: Clone powerlevel10k github repository
    git:
      repo: https://github.com/romkatv/powerlevel10k.git
      dest: ~/powerlevel10k
      clone: yes
      update: yes